# Generated by Django 4.1.2 on 2022-10-06 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='static/img/fotos/%d/%m/%Y/')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todas_receitas.receita')),
            ],
        ),
    ]
