# Generated by Django 4.1.2 on 2022-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0002_alter_receita_data_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='receitas/static/img/fotos'),
        ),
    ]
