# Generated by Django 4.1.2 on 2022-10-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0005_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='receitas/static/img/fotos/%d/%m/%Y'),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
