# Generated by Django 4.1.2 on 2022-10-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0010_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'rendimentos'},
        ),
    ]
