# Generated by Django 4.1.2 on 2022-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0011_alter_receita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='modo_de_preparo',
            field=models.TextField(default=False),
        ),
    ]
