# Generated by Django 4.1.2 on 2022-10-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todas_receitas', '0013_alter_receita_modo_de_preparo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'Receitas'},
        ),
    ]
